Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 50
Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 20
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false